### PR TITLE
Update default language server to python-lsp-server

### PR DESCRIPTION
**Pull request by maresb**
Hello, thanks for the great extension! I would like to update it so that it defaults to using [Python LSP Server](https://github.com/python-lsp/python-lsp-server), since the Palantir version seems abandoned.

Unfortunately I noticed that my VS Code "PROBLEMS" window reports several erroneous warnings from `pyflakes` and `pycodestyle` when using python-lsp-server, while this doesn't happen with Palantir. I don't really understand what's going on there. Any ideas?

### CODE REVIEW

**Comment by jnoortheen** [comment]
One small thing, please checkout https://www.conventionalcommits.org/en/v1.0.0/ 

this format is used to generate changelog

**Comment by maresb** [comment]
@jnoortheen thanks so much for the quick response!

I don't really know JS, so I'm a bit lost. Why is the configuration from package.json not being passed to `pylsp`? Is it on the basis of the config variables starting with `pyls.` with the console script being named `pyls`?

I will look into the "conventional commits", thanks!

**Comment by maresb** [comment]
The linters are disabled when I change all config occurrences of `pyls` to `pylsp`. My latest hunch is that [this](https://github.com/python-lsp/python-lsp-server/blob/5a13db19fbecc25ea565eed1a16545450a6ccac8/pylsp/workspace.py#L102) on the server side must match [this](https://github.com/jnoortheen/vscode-xonsh/blob/feccfa0f625e9a1d64eb00cbb4f8f3cb4de0ee78/src/client.ts#L25) on the client side.

This seems really weird to me; first of all that `vscode-xonsh` has a config namespace of `pyls` instead of `xonsh.pyls` or something. And secondly, let's suppose there was another extension called `vscode-yonsh` which made use of its own Python LS. Does that mean that it's simply impossible to configure them independently?

**Comment by jnoortheen** [comment]
Yep that seems to be the issue. It is hardcoded in the server-side.

**Comment by maresb** [comment]
I think this is now ready to go as a migration from `pyls` to `pylsp`. I will raise my concerns about the configuration variables in a separate issue.

**Comment by jnoortheen** [comment]
looks good. I will merge and create a new release.

**Pull request merged**
